### ISSUE TITLE
Nitpick: Missing mention of screen = top|bottom when disabling 3D

### ISSUE THREAD

**Issue by squirrel-bat** [lovebrew/lovebrew.github.io#14]
## Change:
Please mention `screen` having the values **`top`** and `bottom` instead of `left`, `right`, and `bottom` after disabling Stereoscopic 3D on the Nintendo 3DS by calling `love.graphics.set3D(false)`. :slightly_smiling_face: 

## Where:
![image](https://github.com/user-attachments/assets/5c0fcec4-0195-43a0-9485-ded88428c9f7)
https://lovebrew.org/compatibility/rendering#stereoscopic-3d-depth

**Comment by TurtleP** [comment]
Sorry for the late reply, been busy with life. This was fixed in commit 8c58067da144871b616a86939dc3022097a30fcd.
